TestParameterInjector: Throw a descriptive error message when a provider class should be static.
New exception:

java.lang.IllegalStateException: Could not find a no-arg constructor for CharMatcherProvider, probably because it is a not-static inner class. You can fix this by making CharMatcherProvider static.